

  development:
    adapter: postgresql
    encoding: unicode
    database: postdata
    pool: 5
    username: postgres
    password: 123456
    host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: postdata
  pool: 5
  username: postgres
  password: 123456



